export enum TransactionTypeEnum {
    CARD = 'card',
    MOBILE_MONEY = 'mobile_money',
    VISA = 'visa',
    PAYPAL = 'paypal',
    REFUND = 'refund',
    CREDIT = 'credit',
    DEBIT = 'debit',
    BANK_TRANSFER = 'bank_transfer',
    CASH = 'cash',
    CRYPTOCURRENCY = 'cryptocurrency',
    CHECK = 'check',
    DIRECT_DEBIT = 'direct_debit',
    EWALLET = 'ewallet',
    PREPAID_CARD = 'prepaid_card',
    NET_BANKING = 'net_banking',
    WIRE_TRANSFER = 'wire_transfer',
    POS = 'pos',
    GOOGLE_PAY = 'google_pay',
    APPLE_PAY = 'apple_pay',
    STRIPE = 'stripe',
    SQUARE = 'square'
}
